#pipeline triggers on each new container push to ACR, which has a feature-* tag

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'acr-connection'
  imagePullSecret: 'aksdevops3acr1234-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

resources: 
# repositories:
#  - repository: githubrepo
#    type: github
#    name: vermegi/azure-pipelines-canary-k8s
#    endpoint: vermegi
 containers:
  - container: acrpushdemocontainer      
    type: ACR  
    azureSubscription: armsubscriptionconnection
    resourceGroup: aksdevops3-rg
    registry: aksdevops3acr
    repository: acrpush-demo
    trigger: 
      tags:
        include: 
        - feature-* 

stages: 
- stage: DeployDev
  displayName: Deploy feature to dev

  jobs:
  - deployment: Deploydev
    displayName: Deploy dev
    pool:
      vmImage: $(vmImageName)
    environment: 'aksacrpushdemo.acrpushdemodev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self 

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Build.SourcesDirectory)/**/manifests/deployment.yml
                $(Build.SourcesDirectory)/**/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(resources.container.acrpushdemocontainer.registry)/$(resources.container.acrpushdemocontainer.repository):$(resources.container.acrpushdemocontainer.tag)

